#!/usr/bin/env node

/**
 * @file
 * Binding Component implementation automatically generated by
 * the Social Communication Platform.
 *
 * Characteristics:
 * - Type: SMTP sender.
 */

var mailer = require('./lib/mailer');
var Message = require('scb-node-parser/message');

/**
 * Sends a message a SMTP server.
 * Protocol: SMTP.
 * @param {string} msg - The message to send.
 */
exports.post = function(msg) {
    //msg = JSON.parse(msg);
    console.log('send email %s ' + JSON.stringify(msg));
    console.log('to 1 %s ' + msg._to);
    console.log('to 2 %s ' + msg._to.uniqueName);
    opts = {
        from: msg.getFrom(),
        to: msg._to.uniqueName,
        subject: 'From: ' + msg.getFrom().uniqueName + '. ' + msg.getSubject(),
        body: msg.getMessage()
    }
    console.log('opts %s ', JSON.stringify(opts));
    mailer.sendMail(opts);
};
