#!/usr/bin/env node

/**
 * @file
 * Binding Component implementation automatically generated by
 * the Social Communication Platform.
 *
 * Characteristics:
 * - Type: SMTP sender.
 */

var mailer = require('./lib/mailer');
var Message = require('scb-node-parser/message');

/**
 * Sends a message a SMTP server.
 * Protocol: SMTP.
 * @param {string} msg - The message to send.
 */
exports.post = function(msg) {
    //msg = JSON.parse(msg);
    opts = {
        from: msg.getFrom(),
        to: msg.getTo(),
        subject: 'From: ' + msg.getFrom() + '. ' + msg.getSubject(),
        body: msg.getMessage()
    }
    mailer.sendMail(opts);
};
